In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

# Xử lí chung

In [12]:
# Đọc dữ liệu
df = pd.read_excel("../Education_dataset_V2/04.xeploaiav.xlsx")
df.head()

id                                      mssv  listening  reading   total  \
0  1.0  DA75FFFEXPvAibaEXe8808q51BnmQhHT8REwWMQJ       NULL     NULL    15.0   
1  2.0  336B9F53XPvAibaEXe/jd8ghaf1GTNPSHNuhAHTZ       NULL     NULL    15.0   
2  3.0  67A51DC3XPvAibaEXe/7YVAxOsMwOtCFvKInEQ0e       NULL     NULL    16.0   
3  4.0  387E2EFEXPvAibaEXe96K1aB3B4cKSj8mKKciukN       NULL     NULL    16.0   
4  6.0  13D900A2XPvAibaEXe97wmuqTYuV7bJOKimbzKxM       NULL     NULL    18.0   

    mamh  ghichu  
0   NULL    NULL  
1   NULL    NULL  
2   NULL    NULL  
3   NULL    NULL  
4   NULL    NULL

In [13]:
# In ra các cột của bảng
df.columns

Index(['id', 'mssv', ' listening', ' reading', ' total', ' mamh', ' ghichu'], dtype='object')

In [14]:
# Bỏ khoảng trắng ở tên cột
df.columns = df.columns.str.strip()
df.columns

Index(['id', 'mssv', 'listening', 'reading', 'total', 'mamh', 'ghichu'], dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6349 entries, 0 to 6348
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   id         6343 non-null   float64
 1   mssv       6343 non-null   object 
 2   listening  6343 non-null   object 
 3   reading    6343 non-null   object 
 4   total      6343 non-null   float64
 5   mamh       6343 non-null   object 
 6   ghichu     6343 non-null   object 
dtypes: float64(2), object(5)
memory usage: 347.3+ KB


In [16]:
# Kiểm tra giá trị thiếu
nan_rows = df[df.isna().any(axis=1)]
print(nan_rows)

      id mssv listening reading  total mamh ghichu
1055 NaN  NaN       NaN     NaN    NaN  NaN    NaN
2078 NaN  NaN       NaN     NaN    NaN  NaN    NaN
3186 NaN  NaN       NaN     NaN    NaN  NaN    NaN
4093 NaN  NaN       NaN     NaN    NaN  NaN    NaN
4982 NaN  NaN       NaN     NaN    NaN  NaN    NaN
6091 NaN  NaN       NaN     NaN    NaN  NaN    NaN


In [17]:
df.dropna(inplace=True)

# Xử lí reading và listening

In [18]:
df['listening'].unique()

array([' NULL', '44', '48', '42', '29', '22', '24', '21', '35', '32',
       '19', '23', '28', '16', '34', '47', '43', '18', '31', '33', '39',
       '36', '38', '27', '25', '30', '13', '14', '45', '11', '20', '15',
       '41', '26', '17', '40', '7', '37', '49', '12', '10', '46', '6',
       '9', '1', '50', '8', '5', '0', '2', '4'], dtype=object)

In [19]:
df['reading'].unique()

array([' NULL', '60', '57', '54', '48', '25', '26', '15', '21', '40',
       '34', '17', '28', '47', '39', '37', '23', '59', '64', '51', '58',
       '27', '35', '63', '29', '50', '33', '44', '66', '32', '43', '46',
       '19', '24', '36', '14', '31', '20', '22', '41', '16', '52', '7',
       '42', '38', '12', '49', '56', '30', '45', '55', '10', '61', '18',
       '62', '53', '13', '0', '8', '11', '3', '9', '65', '67', '69', '68'],
      dtype=object)

In [20]:
df['total'].unique()

array([ 15.,  16.,  18.,  19.,  20.,  22.,  23.,  24.,  25.,  26.,  27.,
        28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,
        39.,  40.,  42.,  43.,  44.,  46.,  47.,  48.,  49.,  50.,  51.,
        52.,  53.,  54.,  55.,  56.,  58.,  59.,  60.,   0.,  11.,  13.,
        14.,  17.,  21.,  41.,  45.,  57.,  61.,  62.,  63.,  65.,  66.,
        87.,  83.,  64.,  75.,  90.,  67.,  85.,  72.,  69.,  84.,  88.,
        70.,  68.,  74.,  93.,  95.,  71.,  82.,  91.,  73.,  77.,  78.,
        79.,  81.,  89.,  76.,  86.,  80.,  92.,  94.,  96., 104., 105.,
       106., 112., 110.,  97.,  98., 114.,  99., 103., 109., 113., 102.,
       100., 111., 108., 107., 101.,   6.,  10., 116., 630., 610., 605.,
       600., 595., 590., 585., 580., 575., 570., 565., 560., 555., 545.,
       540., 535., 530., 525., 520., 515., 510., 505., 500., 495., 490.,
       485., 480., 475., 470., 465., 460., 455., 450., 445., 440., 435.,
       430., 425., 420., 415., 410., 405., 400., 39

In [21]:
df['listening'] = df['listening'].replace(' NULL', '0')
df['reading'] = df['reading'].replace(' NULL', '0')

In [22]:
# Chuyển kiểu dữ liệu
df['listening'] = df['listening'].astype(float)
df['reading'] = df['reading'].astype(float)
df['total'] = df['total'].astype(float)

In [23]:
#thay thế các giá trị bị thiếu bằng total/2
df['total'] = df['total'].replace(0, np.nan)
df['listening'] = df['listening'].replace(0, np.nan)
df['listening'] = df['listening'].fillna(round(df['total'].floordiv(2)))

In [24]:
df['reading'] = df['reading'].replace(0, np.nan)
df['reading'] = df['reading'].fillna(df['total'] - df['listening'])

In [25]:
df.isna().sum()

id           0
mssv         0
listening    1
reading      1
total        1
mamh         0
ghichu       0
dtype: int64

In [26]:
df['total'] = df['total'].replace(np.nan, 0)
df['listening'] = df['listening'].replace(np.nan, 0)
df['reading'] = df['reading'].replace(np.nan, 0)

In [27]:
df

id                                      mssv  listening  reading  \
0        1.0  DA75FFFEXPvAibaEXe8808q51BnmQhHT8REwWMQJ        7.0      8.0   
1        2.0  336B9F53XPvAibaEXe/jd8ghaf1GTNPSHNuhAHTZ        7.0      8.0   
2        3.0  67A51DC3XPvAibaEXe/7YVAxOsMwOtCFvKInEQ0e        8.0      8.0   
3        4.0  387E2EFEXPvAibaEXe96K1aB3B4cKSj8mKKciukN        8.0      8.0   
4        6.0  13D900A2XPvAibaEXe97wmuqTYuV7bJOKimbzKxM        9.0      9.0   
...      ...                                       ...        ...      ...   
6344  6383.0  E8A5FA8CXPvAibaEXe/31hnRTOucclruvJrLqfHH       27.0     32.0   
6345  6384.0  B3487295XPvAibaEXe8iDpfibljbVHQ0k0Q2Ad15       28.0     41.0   
6346  6385.0  9166AE22XPvAibaEXe+V8Z3g2JN9F+ODXiTHI+x2       27.0     44.0   
6347  6386.0  2A792560XPvAibaEXe9gkNN06c3nLV4jpNl00QZq       30.0     26.0   
6348  6387.0  E95089F0XPvAibaEXe9S88+OcosOZnhlddS60pjv       33.0     46.0   

      total    mamh   ghichu  
0      15.0    NULL     NULL  
1      15.0    NULL     NULL  
2      16.0    NULL     NULL  
3      16.0    NULL     NULL  
4      18.0    NULL     NULL  
...     ...     ...      ...  
6344   59.0   ENG01     NULL  
6345   69.0   ENG02     NULL  
6346   71.0   ENG02     NULL  
6347   56.0   ENG01     NULL  
6348   79.0   ENG03   NULL);  

[6343 rows x 7 columns]

# Xử lí cột ghi chú

In [28]:
df["ghichu"].unique()

array([' NULL', ' NULL);', ' Qui đổi TOEIC', ' Qui đổi TOEIC);',
       " 'Qui đổi TOEIC'"], dtype=object)

In [29]:
df["ghichu"] = df["ghichu"].str.strip()
df["ghichu"].unique()

array(['NULL', 'NULL);', 'Qui đổi TOEIC', 'Qui đổi TOEIC);',
       "'Qui đổi TOEIC'"], dtype=object)

In [30]:
df["ghichu"] = df["ghichu"].replace("NULL);", "NULL")
df["ghichu"] = df["ghichu"].replace(["Qui đổi TOEIC);", "'Qui đổi TOEIC'"], "Qui đổi TOEIC")
df["ghichu"].unique()

array(['NULL', 'Qui đổi TOEIC'], dtype=object)

# Xử lí xếp loại anh văn

In [31]:
df["total"].unique()

array([ 15.,  16.,  18.,  19.,  20.,  22.,  23.,  24.,  25.,  26.,  27.,
        28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,
        39.,  40.,  42.,  43.,  44.,  46.,  47.,  48.,  49.,  50.,  51.,
        52.,  53.,  54.,  55.,  56.,  58.,  59.,  60.,   0.,  11.,  13.,
        14.,  17.,  21.,  41.,  45.,  57.,  61.,  62.,  63.,  65.,  66.,
        87.,  83.,  64.,  75.,  90.,  67.,  85.,  72.,  69.,  84.,  88.,
        70.,  68.,  74.,  93.,  95.,  71.,  82.,  91.,  73.,  77.,  78.,
        79.,  81.,  89.,  76.,  86.,  80.,  92.,  94.,  96., 104., 105.,
       106., 112., 110.,  97.,  98., 114.,  99., 103., 109., 113., 102.,
       100., 111., 108., 107., 101.,   6.,  10., 116., 630., 610., 605.,
       600., 595., 590., 585., 580., 575., 570., 565., 560., 555., 545.,
       540., 535., 530., 525., 520., 515., 510., 505., 500., 495., 490.,
       485., 480., 475., 470., 465., 460., 455., 450., 445., 440., 435.,
       430., 425., 420., 415., 410., 405., 400., 39

In [32]:
df["total"][df["ghichu"]=="Qui đổi TOEIC"].unique()

array([630., 610., 605., 600., 595., 590., 585., 580., 575., 570., 565.,
       560., 555., 545., 540., 535., 530., 525., 520., 515., 510., 505.,
       500., 495., 490., 485., 480., 475., 470., 465., 460., 455., 450.,
       445., 440., 435., 430., 425., 420., 415., 410., 405., 400., 395.,
       390., 385., 380., 375., 370., 365., 360., 355., 350., 345., 340.,
       335., 330., 325., 320., 315., 310., 305., 300., 295., 290., 285.,
       280., 275., 270., 265., 260., 255., 250., 245., 240., 235., 230.,
       225., 220., 215., 210., 205., 200., 195., 190., 185., 180., 175.,
       170., 165., 160., 155., 150., 145., 140., 135., 125.,  50.,  40.])

In [33]:
df["total"][df["ghichu"]=="NULL"].unique()

array([ 15.,  16.,  18.,  19.,  20.,  22.,  23.,  24.,  25.,  26.,  27.,
        28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,
        39.,  40.,  42.,  43.,  44.,  46.,  47.,  48.,  49.,  50.,  51.,
        52.,  53.,  54.,  55.,  56.,  58.,  59.,  60.,   0.,  11.,  13.,
        14.,  17.,  21.,  41.,  45.,  57.,  61.,  62.,  63.,  65.,  66.,
        87.,  83.,  64.,  75.,  90.,  67.,  85.,  72.,  69.,  84.,  88.,
        70.,  68.,  74.,  93.,  95.,  71.,  82.,  91.,  73.,  77.,  78.,
        79.,  81.,  89.,  76.,  86.,  80.,  92.,  94.,  96., 104., 105.,
       106., 112., 110.,  97.,  98., 114.,  99., 103., 109., 113., 102.,
       100., 111., 108., 107., 101.,   6.,  10., 116.])

In [34]:
df["xl_av"] = np.nan

## Xử lí ghichu Qui đổi TOEIC

In [35]:
def convert_TOEIC_to_xeploai(x):
  if x < 300:
    return 0
  elif x >= 300 and x <= 345:
    return 1
  elif x >= 350 and x <= 395:
    return 2
  elif x >= 400 and x <= 445:
    return 3
  elif x >= 500 and x <= 555:
    return 4
  else:
    return 5
df["xl_av"][df["ghichu"]=="Qui đổi TOEIC"] = df["total"][df["ghichu"]=="Qui đổi TOEIC"].apply(lambda x: convert_TOEIC_to_xeploai(x))

C:\Users\anhdu\AppData\Local\Temp\ipykernel_13000\545039712.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["xl_av"][df["ghichu"]=="Qui đổi TOEIC"] = df["total"][df["ghichu"]=="Qui đổi TOEIC"].apply(lambda x: convert_TOEIC_to_xeploai(x))


## Xử lí ghichu bằng NULL nhưng có điểm total > 120 
## (số điểm anh văn đầu vào tối đa là 120, vượt quá 120 => qui đổi TOEIC)

In [36]:
df["xl_av"][(df["ghichu"] == "NULL") & (df['total'] > 120)] = df["total"][(df["ghichu"] == "NULL") & (df['total'] > 120)].apply(lambda x: convert_TOEIC_to_xeploai(x))

C:\Users\anhdu\AppData\Local\Temp\ipykernel_13000\888273223.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["xl_av"][(df["ghichu"] == "NULL") & (df['total'] > 120)] = df["total"][(df["ghichu"] == "NULL") & (df['total'] > 120)].apply(lambda x: convert_TOEIC_to_xeploai(x))


In [37]:
df[(df["ghichu"] == "NULL") & (df['total'] > 120)]

Empty DataFrame
Columns: [id, mssv, listening, reading, total, mamh, ghichu, xl_av]
Index: []

## Xử lí ghichu bằng NULL

In [38]:
def convert_avdv_to_xeploai(x):
  if x < 40:
    return 0
  elif x >= 40 and x <= 60:
    return 1
  elif x >= 60 and x <= 70:
    return 2
  elif x >= 70 and x <= 80:
    return 3
  elif x >= 80 and x <= 90:
    return 4
  else:
    return 5
df["xl_av"][(df["ghichu"] == "NULL") & (df['total'] <= 120)] = df["total"][(df["ghichu"] == "NULL") & (df['total'] <= 120)].apply(lambda x: convert_avdv_to_xeploai(x))

C:\Users\anhdu\AppData\Local\Temp\ipykernel_13000\32938597.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["xl_av"][(df["ghichu"] == "NULL") & (df['total'] <= 120)] = df["total"][(df["ghichu"] == "NULL") & (df['total'] <= 120)].apply(lambda x: convert_avdv_to_xeploai(x))


In [39]:
df[(df["ghichu"] == "NULL") & (df['total'] <= 120)]

id                                      mssv  listening  reading  \
0        1.0  DA75FFFEXPvAibaEXe8808q51BnmQhHT8REwWMQJ        7.0      8.0   
1        2.0  336B9F53XPvAibaEXe/jd8ghaf1GTNPSHNuhAHTZ        7.0      8.0   
2        3.0  67A51DC3XPvAibaEXe/7YVAxOsMwOtCFvKInEQ0e        8.0      8.0   
3        4.0  387E2EFEXPvAibaEXe96K1aB3B4cKSj8mKKciukN        8.0      8.0   
4        6.0  13D900A2XPvAibaEXe97wmuqTYuV7bJOKimbzKxM        9.0      9.0   
...      ...                                       ...        ...      ...   
6344  6383.0  E8A5FA8CXPvAibaEXe/31hnRTOucclruvJrLqfHH       27.0     32.0   
6345  6384.0  B3487295XPvAibaEXe8iDpfibljbVHQ0k0Q2Ad15       28.0     41.0   
6346  6385.0  9166AE22XPvAibaEXe+V8Z3g2JN9F+ODXiTHI+x2       27.0     44.0   
6347  6386.0  2A792560XPvAibaEXe9gkNN06c3nLV4jpNl00QZq       30.0     26.0   
6348  6387.0  E95089F0XPvAibaEXe9S88+OcosOZnhlddS60pjv       33.0     46.0   

      total    mamh ghichu  xl_av  
0      15.0    NULL   NULL    0.0  
1      15.0    NULL   NULL    0.0  
2      16.0    NULL   NULL    0.0  
3      16.0    NULL   NULL    0.0  
4      18.0    NULL   NULL    0.0  
...     ...     ...    ...    ...  
6344   59.0   ENG01   NULL    1.0  
6345   69.0   ENG02   NULL    2.0  
6346   71.0   ENG02   NULL    3.0  
6347   56.0   ENG01   NULL    1.0  
6348   79.0   ENG03   NULL    3.0  

[4797 rows x 8 columns]

In [40]:
df.drop(columns=["id", "listening", "reading", "mamh", "ghichu"], inplace=True)

In [41]:
df

mssv  total  xl_av
0     DA75FFFEXPvAibaEXe8808q51BnmQhHT8REwWMQJ   15.0    0.0
1     336B9F53XPvAibaEXe/jd8ghaf1GTNPSHNuhAHTZ   15.0    0.0
2     67A51DC3XPvAibaEXe/7YVAxOsMwOtCFvKInEQ0e   16.0    0.0
3     387E2EFEXPvAibaEXe96K1aB3B4cKSj8mKKciukN   16.0    0.0
4     13D900A2XPvAibaEXe97wmuqTYuV7bJOKimbzKxM   18.0    0.0
...                                        ...    ...    ...
6344  E8A5FA8CXPvAibaEXe/31hnRTOucclruvJrLqfHH   59.0    1.0
6345  B3487295XPvAibaEXe8iDpfibljbVHQ0k0Q2Ad15   69.0    2.0
6346  9166AE22XPvAibaEXe+V8Z3g2JN9F+ODXiTHI+x2   71.0    3.0
6347  2A792560XPvAibaEXe9gkNN06c3nLV4jpNl00QZq   56.0    1.0
6348  E95089F0XPvAibaEXe9S88+OcosOZnhlddS60pjv   79.0    3.0

[6343 rows x 3 columns]

In [42]:
# Thống kê số lượng theo trình độ anh văn
count_by_xl_av = df.groupby("xl_av").size()
print(count_by_xl_av)

xl_av
0.0    2067
1.0    2055
2.0     752
3.0     594
4.0     410
5.0     465
dtype: int64


In [43]:
df.to_csv('../data_clean/04.xeploaiav.csv', index=False)
