In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

# Xử lí chung

In [2]:
# Đọc dữ liệu
df = pd.read_excel("../Education_dataset_V2/sinhvien_dtb_hocky.xlsx")
df.head()

mssv  hocky  namhoc  dtbhk  sotchk
0  48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      1    2016   6.45      13
1  48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      2    2016   5.86      17
2  48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      1    2017   6.54      16
3  48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      2    2017   5.67      23
4  48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      1    2018   2.27      21

In [3]:
# In ra các cột của bảng
df.columns

Index(['mssv', 'hocky', 'namhoc', 'dtbhk', 'sotchk'], dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84952 entries, 0 to 84951
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   mssv    84952 non-null  object 
 1   hocky   84952 non-null  int64  
 2   namhoc  84952 non-null  int64  
 3   dtbhk   84952 non-null  float64
 4   sotchk  84952 non-null  int64  
dtypes: float64(1), int64(3), object(1)
memory usage: 3.2+ MB


In [5]:
# Thống kê giá trị NaN ở mỗi cột
df.isna().sum()

mssv      0
hocky     0
namhoc    0
dtbhk     0
sotchk    0
dtype: int64

In [6]:
df["hocky"].unique()

array([1, 2, 3], dtype=int64)

In [7]:
df["namhoc"].unique()

array([2016, 2017, 2018, 2015, 2014, 2019, 2020, 2013, 2021, 2022],
      dtype=int64)

In [8]:
df["dtbhk"].describe()

count    84952.000000
mean         6.714582
std          2.049809
min          0.000000
25%          6.070000
50%          7.250000
75%          8.070000
max         10.000000
Name: dtbhk, dtype: float64

In [9]:
# Có các giá trị outliers: số tín chỉ học kỳ
df["sotchk"].unique()

array([ 13,  17,  16,  23,  21,  12,   6,  20,  15,   8,  19,  18,  24,
        22,   4,   7,   0,  11,  14,   3,  10,   5,  27,  25,  28,  26,
         9,   2,  29,  30,  32,  44,   1, 138, 195,  69, 192], dtype=int64)

In [10]:
df.shape

(84952, 5)

In [11]:
df[df["dtbhk"] < 5]

mssv  hocky  namhoc  dtbhk  sotchk
4      48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      1    2018   2.27      21
11     DC7421E3XPvAibaEXe99yNsueYx+sReTY2489sLU      1    2016   4.73      17
12     DC7421E3XPvAibaEXe99yNsueYx+sReTY2489sLU      2    2016   1.79      15
13     DC7421E3XPvAibaEXe99yNsueYx+sReTY2489sLU      1    2017   4.02      20
14     DC7421E3XPvAibaEXe99yNsueYx+sReTY2489sLU      2    2017   3.89      20
...                                         ...    ...     ...    ...     ...
84939  F6492EF0XPvAibaEXe9Zp44TyFcBSCUKBXJCjJvO      2    2022   4.10       3
84940  68967370XPvAibaEXe9Zp44TyFcBSDcwWhsGcthJ      2    2022   0.00       0
84949  09DE3A51XPvAibaEXe/GEP39G15BdRSEDU3D3+LV      2    2022   0.00       0
84950  CCF627D0XPvAibaEXe+oAybUv81bbkc8L/mx+IhC      2    2022   0.00       0
84951  A6169055XPvAibaEXe81r7KrCH0uc4QKxDeoWYb4      2    2022   0.00       0

[12132 rows x 5 columns]

# Xử lý cột học kỳ

In [12]:
df['hocky_sx'] = np.nan

In [13]:
df_min_nam_hoc = df.groupby('mssv')['namhoc'].transform('min')

In [14]:
df['hocky_sx'] = df.apply(lambda row: row['hocky'] + (row['namhoc'] - df_min_nam_hoc[row.name]) * 2, axis=1)

In [15]:
df

mssv  hocky  namhoc  dtbhk  sotchk  \
0      48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      1    2016   6.45      13   
1      48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      2    2016   5.86      17   
2      48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      1    2017   6.54      16   
3      48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      2    2017   5.67      23   
4      48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      1    2018   2.27      21   
...                                         ...    ...     ...    ...     ...   
84947  EA2A92C2XPvAibaEXe99J3nD1pBZIshWCsT6VhsJ      1    2022   6.70       3   
84948  ED5A0E45XPvAibaEXe/CiPILllTJf8s+lllUG7Kd      1    2022   7.80       3   
84949  09DE3A51XPvAibaEXe/GEP39G15BdRSEDU3D3+LV      2    2022   0.00       0   
84950  CCF627D0XPvAibaEXe+oAybUv81bbkc8L/mx+IhC      2    2022   0.00       0   
84951  A6169055XPvAibaEXe81r7KrCH0uc4QKxDeoWYb4      2    2022   0.00       0   

       hocky_sx  
0             1  
1             2  
2             3  
3             4  
4             5  
...         ...  
84947        15  
84948        15  
84949        12  
84950        14  
84951        12  

[84952 rows x 6 columns]

In [16]:
df[df["hocky_sx"] > 6] 

mssv  hocky  namhoc  dtbhk  sotchk  \
10090  528F8C01XPvAibaEXe8c/asunKa47A4PEbC2JQwZ      3    2017   7.75       8   
10091  528F8C01XPvAibaEXe8c/asunKa47A4PEbC2JQwZ      1    2018   7.75      12   
10098  7A4947EAXPvAibaEXe8c/asunKa47MC7Zfux2sgr      1    2018   7.27      17   
10105  775B0760XPvAibaEXe8c/asunKa47DSKf4pHLmHt      1    2018   7.78      20   
10112  D17C7EEBXPvAibaEXe8c/asunKa47JL/mH8i+PZc      1    2018   8.05      17   
...                                         ...    ...     ...    ...     ...   
84947  EA2A92C2XPvAibaEXe99J3nD1pBZIshWCsT6VhsJ      1    2022   6.70       3   
84948  ED5A0E45XPvAibaEXe/CiPILllTJf8s+lllUG7Kd      1    2022   7.80       3   
84949  09DE3A51XPvAibaEXe/GEP39G15BdRSEDU3D3+LV      2    2022   0.00       0   
84950  CCF627D0XPvAibaEXe+oAybUv81bbkc8L/mx+IhC      2    2022   0.00       0   
84951  A6169055XPvAibaEXe81r7KrCH0uc4QKxDeoWYb4      2    2022   0.00       0   

       hocky_sx  
10090         7  
10091         7  
10098         7  
10105         7  
10112         7  
...         ...  
84947        15  
84948        15  
84949        12  
84950        14  
84951        12  

[19846 rows x 6 columns]

# Xử lý cột sotchk

In [17]:
count_by_sotchk = df.groupby("sotchk").size()
print(count_by_sotchk)

sotchk
0       967
1         5
2       297
3      1548
4      2351
5       184
6       847
7      1421
8      1500
9       588
10     2389
11     1114
12     1879
13     2617
14     4053
15     5070
16     6984
17     7865
18     7102
19     8171
20     7642
21     6095
22     5531
23     3754
24     3191
25      705
26      489
27      244
28      169
29       94
30       51
32        1
44        1
69        1
138      11
192      20
195       1
dtype: int64


* Những giá trị tín chỉ > 30 là không hợp lệ 
* Đưa chúng về = giá trị tín chỉ nhiều nhất (19)

In [18]:
df.loc[df['sotchk'] > 30, 'sotchk'] = 19

In [19]:
count_by_sotchk = df.groupby("sotchk").size()
print(count_by_sotchk)

sotchk
0      967
1        5
2      297
3     1548
4     2351
5      184
6      847
7     1421
8     1500
9      588
10    2389
11    1114
12    1879
13    2617
14    4053
15    5070
16    6984
17    7865
18    7102
19    8206
20    7642
21    6095
22    5531
23    3754
24    3191
25     705
26     489
27     244
28     169
29      94
30      51
dtype: int64


In [20]:
df.isna().sum()

mssv        0
hocky       0
namhoc      0
dtbhk       0
sotchk      0
hocky_sx    0
dtype: int64

In [21]:
df

mssv  hocky  namhoc  dtbhk  sotchk  \
0      48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      1    2016   6.45      13   
1      48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      2    2016   5.86      17   
2      48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      1    2017   6.54      16   
3      48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      2    2017   5.67      23   
4      48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      1    2018   2.27      21   
...                                         ...    ...     ...    ...     ...   
84947  EA2A92C2XPvAibaEXe99J3nD1pBZIshWCsT6VhsJ      1    2022   6.70       3   
84948  ED5A0E45XPvAibaEXe/CiPILllTJf8s+lllUG7Kd      1    2022   7.80       3   
84949  09DE3A51XPvAibaEXe/GEP39G15BdRSEDU3D3+LV      2    2022   0.00       0   
84950  CCF627D0XPvAibaEXe+oAybUv81bbkc8L/mx+IhC      2    2022   0.00       0   
84951  A6169055XPvAibaEXe81r7KrCH0uc4QKxDeoWYb4      2    2022   0.00       0   

       hocky_sx  
0             1  
1             2  
2             3  
3             4  
4             5  
...         ...  
84947        15  
84948        15  
84949        12  
84950        14  
84951        12  

[84952 rows x 6 columns]

In [22]:
df.to_csv('../data_clean/sinhvien_dtb_hocky.csv', index=False)