# Step 1 - Loading the Required Libraries and Modules 

In [3]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

# Step 2 - Read data. Creating train, test

In [4]:
df = pd.read_csv('../result_data/final_v1.csv') 

In [5]:
df

mssv  gioitinh  hedt_ CLC  \
0      BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2       1.0          0   
1      BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2       1.0          0   
2      BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2       1.0          0   
3      BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2       1.0          0   
4      BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2       1.0          0   
...                                         ...       ...        ...   
56180  75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM       1.0          0   
56181  75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM       1.0          0   
56182  75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM       1.0          0   
56183  75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM       1.0          0   
56184  75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM       1.0          0   

       hedt_ CNTN  hedt_ CQUI  hedt_ CTTT  hedt_ KSTN  khoa_CNPM  khoa_HTTT  \
0               0           1           0           0          1          0   
1               0           1           0           0          1          0   
2               0           1           0           0          1          0   
3               0           1           0           0          1          0   
4               0           1           0           0          1          0   
...           ...         ...         ...         ...        ...        ...   
56180           0           1           0           0          0          0   
56181           0           1           0           0          0          0   
56182           0           1           0           0          0          0   
56183           0           1           0           0          0          0   
56184           0           1           0           0          0          0   

       khoa_KHMT  ...  khuvuc_5.0  khuvuc_6.0  khuvuc_7.0 xl_av  namhoc  \
0              0  ...           0           1           0   1.0    2013   
1              0  ...           0           1           0   1.0    2014   
2              0  ...           0           1           0   1.0    2014   
3              0  ...           0           1           0   1.0    2015   
4              0  ...           0           1           0   1.0    2015   
...          ...  ...         ...         ...         ...   ...     ...   
56180          1  ...           0           0           0   1.0    2020   
56181          1  ...           0           0           0   1.0    2020   
56182          1  ...           0           0           0   1.0    2021   
56183          1  ...           0           0           0   1.0    2021   
56184          1  ...           0           0           0   1.0    2022   

      sotchk  hocky_sx     dtbtl  drltl  xl_dtbhk  
0         18         2  6.020000      5         2  
1         26         3  6.525000      4         1  
2         19         4  6.483333      4         2  
3         20         5  6.615000      4         1  
4         19         6  6.562000      4         1  
...      ...       ...       ...    ...       ...  
56180     21         3  7.250000      3         2  
56181     22         4  7.320000      3         3  
56182     22         5  7.535000      3         2  
56183     14         6  7.548000      4         2  
56184     12         7  7.475000      4         2  

[56185 rows x 31 columns]

In [6]:
# Dữ liệu train gồm các khóa 8, 9, 10, 11, 12, 13
data_train = df[df["khoahoc"]<14]

#  Dữ liệu test là khóa 14
data_test = df[df["khoahoc"]>=14]

print("Số mẫu train:", data_train.shape[0])
print("Số mẫu test:", data_test.shape[0])
print("Tỉ lệ tập test: ", data_test.shape[0]/(data_test.shape[0]+data_train.shape[0]))

Số mẫu train: 46501
Số mẫu test: 9684
Tỉ lệ tập test:  0.17235917059713446


In [7]:
data_train.columns

Index(['mssv', 'gioitinh', 'hedt_ CLC', 'hedt_ CNTN', 'hedt_ CQUI',
       'hedt_ CTTT', 'hedt_ KSTN', 'khoa_CNPM', 'khoa_HTTT', 'khoa_KHMT',
       'khoa_KTMT', 'khoa_KTTT', 'khoa_MMT&TT', 'lopsh', 'khoahoc',
       'chuyennganh2', 'xl_tt', 'khuvuc_1.0', 'khuvuc_2.0', 'khuvuc_3.0',
       'khuvuc_4.0', 'khuvuc_5.0', 'khuvuc_6.0', 'khuvuc_7.0', 'xl_av',
       'namhoc', 'sotchk', 'hocky_sx', 'dtbtl', 'drltl', 'xl_dtbhk'],
      dtype='object')

In [8]:
# Khu vực
khuvuc = [col for col in df.columns if col.startswith("khuvuc")]

# Khoa
khoa = [col for col in df.columns if col.startswith("khoa")]

# Hệ đào tạo
hedt = [col for col in df.columns if col.startswith("hedt")]

# Thuộc tính đầu vào
# input = ["gioitinh", "xl_tt", "xl_av", "khoahoc"] + khuvuc + khoa + hedt + ["dtbtl", "drltl"]
input = ["gioitinh", "xl_tt", "xl_av"] + ["hocky_sx", "dtbtl", "drltl"]

# Output
output = "xl_dtbhk"

# Step3 - Building, Predicting, and Evaluating the Neural Network Model

In [9]:
X_train = data_train[input]
y_train = data_train[output]

In [25]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(32,32), activation='relu', solver='adam', max_iter=500)
mlp.fit(X_train,y_train)


MLPClassifier(hidden_layer_sizes=(32, 32), max_iter=500)

In [28]:
for i in range(2, 8):
    X_test = data_test[input][data_test["hocky_sx"]==i]
    y_test = data_test[output][data_test["hocky_sx"]==i]
    print("HK"+str(i), ":", mlp.score(X_test, y_test))

HK2 : 0.6036838978015449
HK3 : 0.5763846622032867
HK4 : 0.5898702903026559
HK5 : 0.6144121365360303
HK6 : 0.5681381957773513
HK7 : 0.5267379679144385


In [29]:
X_test = data_test[input][data_test["hocky_sx"]==2]
predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)


In [30]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[3705 3234  348  516]
 [1496 9346 2943  676]
 [ 308 4311 6151 2754]
 [ 118  822 3004 6769]]
              precision    recall  f1-score   support

           0       0.66      0.47      0.55      7803
           1       0.53      0.65      0.58     14461
           2       0.49      0.45      0.47     13524
           3       0.63      0.63      0.63     10713

    accuracy                           0.56     46501
   macro avg       0.58      0.55      0.56     46501
weighted avg       0.56      0.56      0.56     46501

