# Step 1 - Loading the Required Libraries and Modules 

In [6]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

# Step 2 - Read data. Creating train, test

In [7]:
df = pd.read_csv('../result_data/final_v1.csv') 

In [8]:
df

mssv  gioitinh  hedt_ CLC  \
0      BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2       1.0          0   
1      BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2       1.0          0   
2      BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2       1.0          0   
3      BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2       1.0          0   
4      BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2       1.0          0   
...                                         ...       ...        ...   
56180  75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM       1.0          0   
56181  75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM       1.0          0   
56182  75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM       1.0          0   
56183  75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM       1.0          0   
56184  75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM       1.0          0   

       hedt_ CNTN  hedt_ CQUI  hedt_ CTTT  hedt_ KSTN  khoa_CNPM  khoa_HTTT  \
0               0           1           0           0          1          0   
1               0           1           0           0          1          0   
2               0           1           0           0          1          0   
3               0           1           0           0          1          0   
4               0           1           0           0          1          0   
...           ...         ...         ...         ...        ...        ...   
56180           0           1           0           0          0          0   
56181           0           1           0           0          0          0   
56182           0           1           0           0          0          0   
56183           0           1           0           0          0          0   
56184           0           1           0           0          0          0   

       khoa_KHMT  ...  hocky  namhoc  sotchk hocky_sx     dtbtl drltl  \
0              0  ...      2    2013      18        2  6.020000     5   
1              0  ...      1    2014      26        3  6.525000     4   
2              0  ...      2    2014      19        4  6.483333     4   
3              0  ...      1    2015      20        5  6.615000     4   
4              0  ...      2    2015      19        6  6.562000     4   
...          ...  ...    ...     ...     ...      ...       ...   ...   
56180          1  ...      1    2020      21        3  7.250000     3   
56181          1  ...      2    2020      22        4  7.320000     3   
56182          1  ...      1    2021      22        5  7.535000     3   
56183          1  ...      2    2021      14        6  7.548000     4   
56184          1  ...      1    2022      12        7  7.475000     4   

       dtbhk_truoc  drlhk_truoc  sotctl  xeploai  
0             6.02            5    22.0        2  
1             7.03            3    40.0        1  
2             6.40            3    66.0        2  
3             7.01            4    85.0        1  
4             6.35            5   105.0        1  
...            ...          ...     ...      ...  
56180         6.95            3    28.0        2  
56181         7.46            3    49.0        3  
56182         8.18            4    71.0        2  
56183         7.60            5    93.0        2  
56184         7.11            3   107.0        2  

[56185 rows x 35 columns]

In [9]:
# Dữ liệu train gồm các khóa 8, 9, 10, 11, 12, 13
data_train = df[df["khoahoc"]<14]

#  Dữ liệu test là khóa 14
data_test = df[df["khoahoc"]>=14]

print("Số mẫu train:", data_train.shape[0])
print("Số mẫu test:", data_test.shape[0])
print("Tỉ lệ tập test: ", data_test.shape[0]/(data_test.shape[0]+data_train.shape[0]))

Số mẫu train: 46501
Số mẫu test: 9684
Tỉ lệ tập test:  0.17235917059713446


In [10]:
data_train.columns

Index(['mssv', 'gioitinh', 'hedt_ CLC', 'hedt_ CNTN', 'hedt_ CQUI',
       'hedt_ CTTT', 'hedt_ KSTN', 'khoa_CNPM', 'khoa_HTTT', 'khoa_KHMT',
       'khoa_KTMT', 'khoa_KTTT', 'khoa_MMT&TT', 'lopsh', 'khoahoc',
       'chuyennganh2', 'xl_tt', 'khuvuc_1.0', 'khuvuc_2.0', 'khuvuc_3.0',
       'khuvuc_4.0', 'khuvuc_5.0', 'khuvuc_6.0', 'khuvuc_7.0', 'xl_av',
       'hocky', 'namhoc', 'sotchk', 'hocky_sx', 'dtbtl', 'drltl',
       'dtbhk_truoc', 'drlhk_truoc', 'sotctl', 'xeploai'],
      dtype='object')

In [11]:
# Khu vực
khuvuc = [col for col in df.columns if col.startswith("khuvuc")]

# Khoa
khoa = [col for col in df.columns if col.startswith("khoa")]

# Hệ đào tạo
hedt = [col for col in df.columns if col.startswith("hedt")]

# Thuộc tính đầu vào
# input = ["gioitinh", "xl_tt", "xl_av", "khoahoc"] + khuvuc + khoa + hedt + ["dtbtl", "drltl"]
input = ["gioitinh", "xl_tt", "xl_av"] + ["hocky_sx", "dtbtl", "drltl"]

# Output
output = "xeploai"

# Step3 - Building, Predicting, and Evaluating the Neural Network Model

In [12]:
X_train = data_train[input]
y_train = data_train[output]

In [13]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(32,32), activation='relu', solver='adam', max_iter=500)
mlp.fit(X_train,y_train)


MLPClassifier(hidden_layer_sizes=(32, 32), max_iter=500)

In [14]:
for i in range(2, 8):
    X_test = data_test[input][data_test["hocky_sx"]==i]
    y_test = data_test[output][data_test["hocky_sx"]==i]
    print("HK"+str(i), ":", mlp.score(X_test, y_test))

HK2 : 0.6096256684491979
HK3 : 0.5611685940353013
HK4 : 0.5923409512044472
HK5 : 0.6201011378002529
HK6 : 0.5681381957773513
HK7 : 0.5254010695187166


In [15]:
X_test = data_test[input][data_test["hocky_sx"]==2]
predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)


In [16]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[4083 2854  463  403]
 [1774 8726 3342  619]
 [ 383 3853 6592 2696]
 [ 173  692 3179 6669]]
              precision    recall  f1-score   support

           0       0.64      0.52      0.57      7803
           1       0.54      0.60      0.57     14461
           2       0.49      0.49      0.49     13524
           3       0.64      0.62      0.63     10713

    accuracy                           0.56     46501
   macro avg       0.58      0.56      0.57     46501
weighted avg       0.56      0.56      0.56     46501



In [17]:
df['namhoc'].value_counts()

2019    9107
2020    8736
2018    8042
2017    7144
2021    6367
2016    6210
2015    4492
2014    2703
2022    2469
2013     915
Name: namhoc, dtype: int64

In [18]:
df.columns

Index(['mssv', 'gioitinh', 'hedt_ CLC', 'hedt_ CNTN', 'hedt_ CQUI',
       'hedt_ CTTT', 'hedt_ KSTN', 'khoa_CNPM', 'khoa_HTTT', 'khoa_KHMT',
       'khoa_KTMT', 'khoa_KTTT', 'khoa_MMT&TT', 'lopsh', 'khoahoc',
       'chuyennganh2', 'xl_tt', 'khuvuc_1.0', 'khuvuc_2.0', 'khuvuc_3.0',
       'khuvuc_4.0', 'khuvuc_5.0', 'khuvuc_6.0', 'khuvuc_7.0', 'xl_av',
       'hocky', 'namhoc', 'sotchk', 'hocky_sx', 'dtbtl', 'drltl',
       'dtbhk_truoc', 'drlhk_truoc', 'sotctl', 'xeploai'],
      dtype='object')

In [19]:
max_price = df['sotctl'].max()
min_price = df['sotctl'].min()

print('Giá trị lớn nhất là:', max_price)
print('Giá trị nhỏ nhất là:', min_price)

Giá trị lớn nhất là: 309.0
Giá trị nhỏ nhất là: 0.0


In [20]:
df['sotctl'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 56185 entries, 0 to 56184
Series name: sotctl
Non-Null Count  Dtype  
--------------  -----  
56185 non-null  float64
dtypes: float64(1)
memory usage: 439.1 KB


In [21]:
df

mssv  gioitinh  hedt_ CLC  \
0      BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2       1.0          0   
1      BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2       1.0          0   
2      BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2       1.0          0   
3      BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2       1.0          0   
4      BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2       1.0          0   
...                                         ...       ...        ...   
56180  75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM       1.0          0   
56181  75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM       1.0          0   
56182  75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM       1.0          0   
56183  75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM       1.0          0   
56184  75AD7B4AXPvAibaEXe8xMCTZ03/BewoGrWSt0ZXM       1.0          0   

       hedt_ CNTN  hedt_ CQUI  hedt_ CTTT  hedt_ KSTN  khoa_CNPM  khoa_HTTT  \
0               0           1           0           0          1          0   
1               0           1           0           0          1          0   
2               0           1           0           0          1          0   
3               0           1           0           0          1          0   
4               0           1           0           0          1          0   
...           ...         ...         ...         ...        ...        ...   
56180           0           1           0           0          0          0   
56181           0           1           0           0          0          0   
56182           0           1           0           0          0          0   
56183           0           1           0           0          0          0   
56184           0           1           0           0          0          0   

       khoa_KHMT  ...  hocky  namhoc  sotchk hocky_sx     dtbtl drltl  \
0              0  ...      2    2013      18        2  6.020000     5   
1              0  ...      1    2014      26        3  6.525000     4   
2              0  ...      2    2014      19        4  6.483333     4   
3              0  ...      1    2015      20        5  6.615000     4   
4              0  ...      2    2015      19        6  6.562000     4   
...          ...  ...    ...     ...     ...      ...       ...   ...   
56180          1  ...      1    2020      21        3  7.250000     3   
56181          1  ...      2    2020      22        4  7.320000     3   
56182          1  ...      1    2021      22        5  7.535000     3   
56183          1  ...      2    2021      14        6  7.548000     4   
56184          1  ...      1    2022      12        7  7.475000     4   

       dtbhk_truoc  drlhk_truoc  sotctl  xeploai  
0             6.02            5    22.0        2  
1             7.03            3    40.0        1  
2             6.40            3    66.0        2  
3             7.01            4    85.0        1  
4             6.35            5   105.0        1  
...            ...          ...     ...      ...  
56180         6.95            3    28.0        2  
56181         7.46            3    49.0        3  
56182         8.18            4    71.0        2  
56183         7.60            5    93.0        2  
56184         7.11            3   107.0        2  

[56185 rows x 35 columns]